main/urls.py
from django.urls import path, include
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth.decorators import login_required

from .views.base import DefaultRedirect
from .views.movement_lists import MovementLists, MovementListsAdd,\
    MovementListEdit, MovementListDelete, MovementListHistory
from .views.movement_list_entries import MovementListEntries,\
    MovementListEntriesAdd, MovementListEntryEdit, MovementListEntryDelete,\
    MovementListEntryHistory, movement_list_entries_PDF


accounts_urls = [
    path(
        "accounts/login/",
        LoginView.as_view(redirect_authenticated_user=True),
        name="login"
    ),
    path("accounts/logout/", LogoutView.as_view(), name="logout"),
]

movement_list_entries_urlpatterns = [
    path(
        "entries/",
        MovementListEntries.as_view(),
        name="movement-list-entries",
    ),
    path(
        "entries/print/",
        movement_list_entries_PDF,
        name="movement-list-entries-print",
    ),
    path(
        "entries/add/",
        login_required(MovementListEntriesAdd.as_view()),
        name="movement-list-entries-add",
    ),
    path(
        "entries/<int:entry_id>/edit/",
        login_required(MovementListEntryEdit.as_view()),
        name="movement-list-entry-edit",
    ),
    path(
        "entries/<int:entry_id>/delete/",
        login_required(MovementListEntryDelete.as_view()),
        name="movement-list-entry-delete",
    ),
    path(
        "entries/<int:entry_id>/history/",
        MovementListEntryHistory.as_view(),
        name="movement-list-entry-history",
    ),
]

movement_lists_urlpatterns = [
    path(
        "lists/",
        MovementLists.as_view(),
        name="movement-lists",
    ),
    path(
        "lists/<int:list_id>/",
        include(movement_list_entries_urlpatterns),
    ),
    path(
        "lists/add/",
        login_required(MovementListsAdd.as_view()),
        name="movement-lists-add",
    ),
    path(
        "lists/<int:list_id>/edit/",
        login_required(MovementListEdit.as_view()),
        name="movement-list-edit",
    ),
    path(
        "lists/<int:list_id>/delete/",
        login_required(MovementListDelete.as_view()),
        name="movement-list-delete",
    ),
    path(
        "lists/<int:list_id>/history/",
        MovementListHistory.as_view(),
        name="movement-list-history",
    ),
]

urlpatterns = [
    path(
        "",
        DefaultRedirect.as_view(),
        {"facility_slug": "shanuch-mine"},
        name="redirect-to-default-facility",
    ),
    path(
        "facility/<slug:facility_slug>/",
        include(movement_lists_urlpatterns),
    ),
] + accounts_urls

main/models/facility.py
from django.db import models
from django.urls import reverse


class FacilityObject(models.Model):

    name = models.CharField(
        "Название производственного объекта",
        max_length=100,
        unique=True
    )
    slug = models.SlugField(
        "Уникальная строка идентификатор (slug)",
        max_length=100,
        unique=True
    )

    def get_url_kwargs(self):
        kwargs = {
            "facility_slug": self.slug,
        }
        return kwargs

    def get_absolute_url(self):
        kwargs = self.get_url_kwargs()
        return reverse(
            "movement-lists",
            kwargs=kwargs
        )

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Производственный объект"
        verbose_name_plural = "Производственные объекты"

main/models/history.py
from django.db import models
from django.contrib.auth import get_user_model


class HistoryMixin(models.Model):

    modified_by = models.ForeignKey(
        get_user_model(),
        on_delete=models.SET_NULL,
        null=True
    )
    modified_datetime = models.DateTimeField("Время внесения изменений")
    serialized_prev_delta = models.TextField("Данные до изменения")
    serialized_post_delta = models.TextField("Данные после изменения")

    class Meta:
        abstract = True

main/models/lists.py
from django.db import models
from django.urls import reverse
from django.contrib.auth import get_user_model

from .history import HistoryMixin
from .facility import FacilityObject
from ..utils import datetime_to_current_tz


class MovementList(models.Model):

    facility = models.ForeignKey(
        FacilityObject,
        on_delete=models.CASCADE,
        verbose_name="Производственный объект"
    )

    ARRIVING = "ARR"
    LEAVING = "LVN"
    TYPES_OF_LIST = [
        (ARRIVING, "Заезд"),
        (LEAVING, "Выезд"),
    ]
    list_type = models.CharField(
        "Тип списка",
        max_length=3,
        choices=TYPES_OF_LIST,
        default=ARRIVING
    )
    scheduled_datetime = models.DateTimeField("Дата и время заезда/выезда")
    creator = models.ForeignKey(
        get_user_model(),
        on_delete=models.SET_NULL,
        null=True,
        verbose_name="Кем создана"
    )
    creation_datetime = models.DateTimeField(
        "Время создания",
        auto_now_add=True
    )
    last_modified = models.DateTimeField(
        "Время последнего изменения модели",
        auto_now=True
    )
    was_modified = models.BooleanField(
        "Был ли список изменен?",
        default=False
    )
    is_deleted = models.BooleanField(
        "Удалён?",
        default=False
    )
    place = models.CharField(
        "Место заезда/выезда",
        max_length=255,
        blank=True,
    )
    watch = models.CharField(
        "Вахта",
        max_length=255,
        blank=True,
    )

    @property
    def list_type_humanize(self):
        """
        Метод возвращает человекочитаемую строку,
        определяющую тип списка в именительном падеже
        единственного числа.
        Например: "заезд" или "выезд".
        """
        arriving_value = self.TYPES_OF_LIST[0][1]
        leaving_value = self.TYPES_OF_LIST[1][1]

        if self.list_type == self.ARRIVING:
            list_type = arriving_value
        else:
            list_type = leaving_value

        humanize = list_type.lower()
        return humanize

    @property
    def was_changed(self):
        """
        Возвращает True, если запись была изменена, иначе False
        """
        return self.was_modified

    def get_url_kwargs(self):
        return {
            "facility_slug": self.facility.slug,
            "list_id": self.pk,
        }

    def get_absolute_url(self):
        return reverse("movement-list-entries", kwargs=self.get_url_kwargs())

    def get_add_url(self):
        return reverse("movement-lists-add", args=[self.facility.slug])

    def get_delete_url(self):
        return reverse("movement-list-delete", kwargs=self.get_url_kwargs())

    def get_edit_url(self):
        return reverse("movement-list-edit", kwargs=self.get_url_kwargs())

    def get_history_url(self):
        return reverse("movement-list-history", kwargs=self.get_url_kwargs())

    def is_creator(self, user):
        return self.creator == user

    def has_change_perm(self, user):
        is_creator = self.is_creator(user)
        can_change_owned = user.has_perm("main.change_owned_movementlist")
        can_change = user.has_perm("main.change_movementlist")
        return is_creator and can_change_owned or can_change

    def has_delete_perm(self, user):
        is_creator = self.is_creator(user)
        can_delete_owned = user.has_perm("main.delete_owned_movementlist")
        can_delete = user.has_perm("main.delete_movementlist")
        return is_creator and can_delete_owned or can_delete

    def __str__(self):
        return "%s на %s" % (
            self.list_type_humanize.title(),
            datetime_to_current_tz(
                self.scheduled_datetime
            ).strftime("%d.%m.%Y %H:%M"),
        )

    class Meta:

        verbose_name = "Список заездов/выездов"
        verbose_name_plural = "Списки заездов/выездов"

        permissions = [
            (
                "change_owned_movementlist",
                "Право изменения списка созданного пользователем"
            ),
            (
                "delete_owned_movementlist",
                "Право удаления списка созданного пользователем"
            ),
            (
                "set_watch_field",
                "Право установки значения вахты",
            )
        ]


class MovementListHistory(HistoryMixin):

    modified_list = models.ForeignKey(
        MovementList,
        on_delete=models.CASCADE
    )

    class Meta:
        verbose_name = "Состояние списка"
        verbose_name_plural = "Состояния списков"

main/forms.py
from django import forms
from django.utils import timezone
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit

from .models import MovementList, Employee, MovementEntry
from .widgets import ListTextWidget


class CustomUserCreationForm(UserCreationForm):

    class Meta:
        model = get_user_model()
        fields = UserCreationForm._meta.fields +\
            ("first_name", "last_name", "patronymic", "position")


class CustomUserChangeForm(UserChangeForm):
    pass


class CreateMovementListForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        _user_perms = kwargs.pop("perms", None)
        super(CreateMovementListForm, self).__init__(*args, **kwargs)
        if "main.set_watch_field" not in _user_perms:
            self.fields["watch"].widget = forms.HiddenInput()

    field_order = [
        "list_type",
        "move_date",
        "move_time",
        "place",
    ]

    move_date = forms.DateField(
        widget=forms.DateInput(
            attrs={
                "placeholder": "25.10.2020",
                "type": "date",
                "min": timezone.now().strftime("%Y-%m-%d")
            }
        ),
        label="Дата"
    )
    move_time = forms.TimeField(
        widget=forms.TimeInput(
            attrs={
                "placeholder": "14:30",
                "type": "time",
            }
        ),
        label="Время"
    )

    class Meta:
        model = MovementList
        fields = ["list_type", "place", "watch"]
        widgets = {
            "place": forms.TextInput(
                attrs={
                    "placeholder": "С какого места выезжает/заезжает сотрудник"
                },
            ),
        }


class EditMovementListForm(forms.Form):

    def __init__(self, *args, **kwargs):
        _user_perms = kwargs.pop("perms", None)
        super(EditMovementListForm, self).__init__(*args, **kwargs)
        if "main.set_watch_field" not in _user_perms:
            self.fields["watch"].widget = forms.HiddenInput()

    move_date = forms.DateField(
        widget=forms.DateInput(
            format=('%Y-%m-%d'),
            attrs={
                "type": "date",
                "min": timezone.now().strftime("%Y-%m-%d")
            }
        ),
        label="Дата"
    )
    move_time = forms.TimeField(
        widget=forms.TimeInput(
            attrs={
                "type": "time",
            }
        ),
        label="Время"
    )
    place = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "placeholder": "С какого места выезжает/заезжает сотрудник",
            },
        ),
        label="Место заезда/выезда",
        required=False
    )
    watch = forms.CharField(
        label="Вахта",
        required=False,
    )


class CreateMovementEntryForm(forms.Form):

    first_name = forms.CharField(
        min_length=2,
        max_length=40,
        label="Имя сотрудника",
    )
    last_name = forms.CharField(
        min_length=2,
        max_length=40,
        label="Фамилия сотрудника",
    )
    patronymic = forms.CharField(
        min_length=2,
        max_length=40,
        label="Отчество сотрудника",
        required=False,
    )
    position = forms.CharField(
        min_length=0,
        max_length=100,
        label="Должность",
        required=False,
    )

    is_senior = forms.BooleanField(
        label="Старший",
        required=False,
    )

    field_order = [
        "first_name",
        "last_name",
        "patronymic",
        "position",
    ]

    def __init__(self, *args, **kwargs):
        _suggestions = kwargs.pop("suggestions", None)
        _user_perms = kwargs.pop("perms", None)
        super(CreateMovementEntryForm, self).__init__(*args, **kwargs)

        self.fields["first_name"].widget = ListTextWidget(
            attrs={"placeholder": "Иван", "autocomplete": "off"},
            data_list=_suggestions.get("first_name", []),
            name="first_name_sug"
        )
        self.fields["last_name"].widget = ListTextWidget(
            attrs={"placeholder": "Иванов", "autocomplete": "off"},
            data_list=_suggestions.get("last_name", []),
            name="last_name_sug"
        )
        self.fields["patronymic"].widget = ListTextWidget(
            attrs={"placeholder": "Иванович", "autocomplete": "off"},
            data_list=_suggestions.get("patronymic", []),
            name="patronymic_sug"
        )
        self.fields["position"].widget = ListTextWidget(
            attrs={"placeholder": "Водитель", "autocomplete": "off"},
            data_list=_suggestions.get("position", []),
            name="position_sug",
        )

        if "main.can_set_is_senior" not in _user_perms:
            self.fields["is_senior"].widget = forms.HiddenInput()


class EditMovementEntryForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        _user_perms = kwargs.pop("perms", None)
        super(EditMovementEntryForm, self).__init__(*args, **kwargs)

        if "main.can_set_is_senior" not in _user_perms:
            self.fields["is_senior"].widget = forms.HiddenInput()

    class Meta:
        model = Employee
        fields = "__all__"


class SearchEntryForm(forms.Form):

    def __init__(self, action, *args, **kwargs):
        _suggestions = kwargs.pop("suggestions", None)
        super().__init__(*args, **kwargs)
        self.helper = FormHelper(self)
        self.helper.disable_csrf = True
        self.helper.form_method = "GET"
        self.helper.form_action = action
        self.helper.add_input(Submit("submit", "Найти"))
        self.fields["search_request"].widget = ListTextWidget(
            attrs={
                "placeholder": "Иван Иванов Иванович",
                "autocomplete": "off"
            },
            data_list=_suggestions,
            name="search_request"
        )

    PREDICATS = [
        ("EMPLOYEES", "ФИО сотрудника"),
        ("USERS", "ФИО ответственного"),
    ]

    search_request = forms.CharField(label="Запрос")
    predicat = forms.ChoiceField(
        label="Искать по",
        widget=forms.Select(),
        choices=PREDICATS,
    )


class SearchListForm(forms.Form):

    def __init__(self, action, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper(self)
        self.helper.disable_csrf = True
        self.helper.form_method = "GET"
        self.helper.form_action = action
        self.helper.add_input(Submit("submit", "Найти"))

    search_date = forms.DateField(
        widget=forms.DateInput(
            attrs={
                "type": "date",
                "min": timezone.now().strftime("%Y-%m-%d")
            }
        ),
        label="Дата"
    )

main/views/base.py
from django.views.generic.base import RedirectView


class DefaultRedirect(RedirectView):
    """
    Редирект на страницу производственного объекта по умолчанию
    """

    permanent = False
    pattern_name = "movement-lists"

main/views/mixins.py
from django.shortcuts import get_object_or_404, get_list_or_404

from ..models import FacilityObject, MovementList


class FacilityMixin:

    @property
    def related_facility(self):
        return get_object_or_404(
            FacilityObject, slug=self.kwargs["facility_slug"]
        )

    @property
    def all_facilities(self):
        return get_list_or_404(FacilityObject.objects.all())


class FacilityListMixin(FacilityMixin):

    @property
    def related_list(self):
        return get_object_or_404(
            MovementList, pk=self.kwargs["list_id"]
        )

main/templates/main/movement-lists/movement-list-delete.html
{% extends "../../base/base.html" %}

{% load crispy_forms_tags %}

{% block meta_title %}
Подтверждение удаления
{% endblock meta_title %}

{% block main_content %}
<div class="container-lg">
  <div class="row justify-content-center">
    <div class="col-md-6 d-flex justify-content-center">
      <div class="card mt-4">
        <div class="card-body">
          <h2 class="card-title h5">Подтверждение удаления</h5>
          <p class="card-text">
          Вы уверены, что хотите удалить этот список?<br>
          После этого действия со списком будут недоступны
          </p>
          <form action="{% url 'movement-list-delete' facility_slug=related_facility.slug list_id=related_list.pk %}" method="POST">
            {% csrf_token %}
            {{ form|crispy }}
            <div class="d-flex">
              {% include "../../includes/backbtn.html" %}
              <button type="submit" class="btn btn-danger ml-auto">Подтвердить</button>
            </div>
          </form>
        </div>  
      </div>
    </div>
  </div>
</div>
{% endblock main_content %}

main/templates/main/movement-lists/movement-list-edit.html
{% extends "../../base/base.html" %}

{% load breadcrumbs %}

{% block meta_title %}
Редактирование
{% endblock meta_title %}

{% block main_content %}
<div class="container-lg">
  <div class="row">
    <div class="col-md">
      {% breadcrumbs links %}
      <div class="card mt-4">
        {% url 'movement-list-edit' facility_slug=related_facility.slug list_id=related_list.pk as action %}
        {% with title="Редактирование списка" action=action method="POST" form=form button_value="Подтвердить" %}
        {% include "../../includes/crispy-form.html" %}
        {% endwith %}
      </div>
    </div>
  </div>
</div>
{% endblock main_content %}

main/templates/main/movement-lists/movement-list-history.html
{% extends "../../base/base.html" %}

{% load breadcrumbs %}

{% block meta_title %}
История изменений
{% endblock meta_title %}

{% block main_content %}
<div class="container-lg">
  <div class="row">
    <div class="col-md">
      {% breadcrumbs links %}
    </div>
  </div>
  <div class="row">
    <div class="col-md">
      <div class="mt-4">
        {% if history_entries %}
        <ul class="list-unstyled">
          {% for entry in history_entries %}
          <li class="card shadow-sm mt-2">
            <div class="card-body">
              <h4 class="card-title h5">
              Перенос с {{ entry.prev_change.scheduled_datetime|date:"d E Y H:i" }} 
              на {{ entry.post_change.scheduled_datetime|date:"d E Y H:i" }}
              </h4>
              <p class="card-text">
              {{ entry.entry.modified_by.initials }} в {{ entry.entry.modified_datetime|date:"H:i d.m.Y" }}
              </p>
            </div>
          </li>
          {% endfor %}
        </ul>
        {% else %}
        <h3 class="h5 card-title">Нет изменений</h2>
        {% endif %}
      </div>
    </div>
  </div>
</div>
{% endblock main_content %}

main/templates/main/movement-lists/movement-lists-add.html
{% extends "../../base/base.html" %}

{% block meta_title %}
{{ related_facility.name|title }} | Добавление списка
{% endblock meta_title %}

{% block main_content %}
<div class="container-lg">
  <div class="row">
    <div class="col-md">
      <ul class="nav nav-pills">
        <li class="nav-item">
          <a class="nav-link" href="{{ related_facility.get_absolute_url }}">Списки</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" href="{% url 'movement-lists-add' facility_slug=related_facility.slug %}">
          Добавить список
          <i class="fas fa-plus-circle"></i>
          </a>
        </li>
        <li class="nav-item ml-auto">
          {% include "../../includes/backbtn.html" %}
        </li>
      </ul>
    </div>
  </div>

  <div class="row mt-2">
    <div class="col-md">
      <div class="card mt-4">
        {% url 'movement-lists-add' facility_slug=related_facility.slug as action %}
        {% with title="Добавление списка" action=action method="POST" form=form button_value="Создать" %}
        {% include "../../includes/crispy-form.html" %}
        {% endwith %}
      </div>
    </div>
  </div>
</div>
{% endblock main_content %}

main/templates/main/movement-lists/movement-lists.html
{% extends "../../base/base.html" %}

{% load crispy_forms_tags %}

{% block meta_title %}
{{ related_facility.name }} | Списки
{% endblock meta_title %}

{% block main_content %}
<section class="container-lg">
  <header>
    <nav class="row">
      <div class="col-md-12">
      {% if messages %}
      <ul class="list-unstyled">
        {% for message in messages %}
        <li class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
          {{ message }}
          <button type="button" class="close" data-dismiss="alert" aria-label="Закрыть">
            <span aria-hidden="true"><i class="fas fa-times"></i></span>
          </button>
        </li>
        {% endfor %}
      </ul>
      {% endif %}
      </div>
      {% if perms.main.add_movementlist %}
      <div class="col-md-12 mb-4">
        <ul class="nav nav-pills">
          <li class="nav-item">
            <a class="nav-link active" href="{{ related_facility.get_absolute_url }}">Списки</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'movement-lists-add' facility_slug=related_facility.slug %}">
            Добавить список
            <i class="fas fa-plus-circle"></i>
            </a>
          </li>
        </ul>
      </div>
      {% endif %}
    </nav>
  </header>

  <div class="row">
    <div class="col-md dropdown show d-flex align-items-center">
      <span class="mr-2">Показывать</span>
      <div>
        <a class="btn btn-outline-primary dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          {{show}}
        </a>

        <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
          <a class="dropdown-item" href="{{ request.path }}">все</a>
          <a class="dropdown-item" href="{{ request.path }}?show=arrivals">только заезды</a>
          <a class="dropdown-item" href="{{ request.path }}?show=departures">только выезды</a>
        </div>
      </div>
      <div class="nav-item btn-group ml-auto" role="group">
        <button
          type="button"
          class="btn btn-outline-primary"
          data-toggle="modal"
          data-target="#searchModal"
        >
          Поиск
        </button>
        {% if request.GET.search_date %}
        <a class="btn btn-outline-primary" href="{{ related_facility.get_absolute_url }}">Сбросить фильтр</a>
        {% endif %}
      </div>
    </div>
  </div>

  <div class="row mt-2">
    <div class="col-md">
      {% if movement_lists %}
      <ul class="list-unstyled">
        {% for mlist in movement_lists %}
        <li class="mt-2">
            <div class="card shadow-sm">
              <div class="card-body d-flex align-items-center flex-row p-3">
                <div>
                  {% if user.is_authenticated %}
                    <h5 class="card-title">
                    {% if mlist.obj.is_deleted %}
                      <del>
                        {{ mlist.obj.list_type_humanize|title }} на {{ mlist.obj.scheduled_datetime|date:"d E Y H:i" }}
                      </del>
                    {% else %}
                      {{ mlist.obj.list_type_humanize|title }} на {{ mlist.obj.scheduled_datetime|date:"d E Y H:i" }}
                    {% endif %}
                      {% if mlist.obj.was_changed %}
                      <span class="badge badge-info ml-1">изменён</span>
                      {% endif %}
                      {% if mlist.obj.is_deleted %}
                      <span class="badge badge-danger ml-1">удалён</span>
                      {% endif %}
                    </h5>
                    <p class="card-text">
                      Создан {{ mlist.obj.creation_datetime }} ответственным {{ mlist.obj.creator.initials }}
                    </p>
                  {% else %}
                    <h5 class="card-text">
                      {% if mlist.obj.is_deleted %}
                        <del>
                          {{ mlist.obj.list_type_humanize|title }} на {{ mlist.obj.scheduled_datetime|date:"d E Y H:i" }}
                        </del>
                      {% else %}
                        {{ mlist.obj.list_type_humanize|title }} на {{ mlist.obj.scheduled_datetime|date:"d E Y H:i" }}
                      {% endif %}
                      {% if mlist.obj.was_changed %}
                      <span class="badge badge-info ml-1">изменён</span>
                      {% endif %}
                      {% if mlist.obj.is_deleted %}
                      <span class="badge badge-danger ml-1">удалён</span>
                      {% endif %}
                    </h5>
                  {% endif %}
                </div>
                <div class="d-flex align-items-center ml-auto" role="group" aria-label="Управление списком">
                  <div class="mr-2">
                    {% include "../../includes/options.html" with obj=mlist.obj can_change=mlist.can_change can_delete=mlist.can_delete %}
                  </div>
                  <a href="{{ mlist.obj.get_absolute_url }}" class="btn btn-outline-primary">Перейти</a>
                </div>
              </div>
            </div>
          </li>
        {% endfor %}
      </ul>
      {% else %}
      <h2 class="h5 mt-4">Списки отсутствуют</h2>
      {% endif %}
    </div>
  </div>

  {% if paginator.num_pages > 1 %}
  <footer class="row mt-4">
    <div class="col">
      {% include "../../includes/paginator.html" %}
    </div>
  </footer>
  {% endif %}
</section>

<div class="modal fade" id="searchModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Поиск по дате</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true"><i class="fas fa-times"></i></span>
        </button>
      </div>
      <div class="modal-body">
        {% crispy search_form search_form.helper %}
      </div>
    </div>
  </div>
</div>
{% endblock main_content %}