main/urls.py
from django.urls import path, include
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth.decorators import login_required

from .views.base import DefaultRedirect
from .views.movement_lists import MovementLists, MovementListsAdd,\
    MovementListEdit, MovementListDelete, MovementListHistory
from .views.movement_list_entries import MovementListEntries,\
    MovementListEntriesAdd, MovementListEntryEdit, MovementListEntryDelete,\
    MovementListEntryHistory, movement_list_entries_PDF


accounts_urls = [
    path(
        "accounts/login/",
        LoginView.as_view(redirect_authenticated_user=True),
        name="login"
    ),
    path("accounts/logout/", LogoutView.as_view(), name="logout"),
]

movement_list_entries_urlpatterns = [
    path(
        "entries/",
        MovementListEntries.as_view(),
        name="movement-list-entries",
    ),
    path(
        "entries/print/",
        movement_list_entries_PDF,
        name="movement-list-entries-print",
    ),
    path(
        "entries/add/",
        login_required(MovementListEntriesAdd.as_view()),
        name="movement-list-entries-add",
    ),
    path(
        "entries/<int:entry_id>/edit/",
        login_required(MovementListEntryEdit.as_view()),
        name="movement-list-entry-edit",
    ),
    path(
        "entries/<int:entry_id>/delete/",
        login_required(MovementListEntryDelete.as_view()),
        name="movement-list-entry-delete",
    ),
    path(
        "entries/<int:entry_id>/history/",
        MovementListEntryHistory.as_view(),
        name="movement-list-entry-history",
    ),
]

movement_lists_urlpatterns = [
    path(
        "lists/",
        MovementLists.as_view(),
        name="movement-lists",
    ),
    path(
        "lists/<int:list_id>/",
        include(movement_list_entries_urlpatterns),
    ),
    path(
        "lists/add/",
        login_required(MovementListsAdd.as_view()),
        name="movement-lists-add",
    ),
    path(
        "lists/<int:list_id>/edit/",
        login_required(MovementListEdit.as_view()),
        name="movement-list-edit",
    ),
    path(
        "lists/<int:list_id>/delete/",
        login_required(MovementListDelete.as_view()),
        name="movement-list-delete",
    ),
    path(
        "lists/<int:list_id>/history/",
        MovementListHistory.as_view(),
        name="movement-list-history",
    ),
]

urlpatterns = [
    path(
        "",
        DefaultRedirect.as_view(),
        {"facility_slug": "shanuch-mine"},
        name="redirect-to-default-facility",
    ),
    path(
        "facility/<slug:facility_slug>/",
        include(movement_lists_urlpatterns),
    ),
] + accounts_urls

main/models/entries.py
from django.db import models
from django.urls import reverse
from django.core import serializers
from django.contrib.auth import get_user_model

from .person import Employee
from .lists import MovementList
from .history import HistoryMixin


class MovementEntryManager(models.Manager):

    def get_autocomplete_suggestions(self, field):
        entries = super().all().distinct()
        values = entries.values_list("employee__" + field, flat=True)
        users_values = entries.values_list("creator__" + field, flat=True)
        values = list(values) + list(users_values)
        return values

    def get_not_deleted(self):
        return super().all().filter(is_deleted=False)


class MovementEntry(models.Model):
    """
    Запись содержащая информацию о заезде/выезде
    сотрудников на производственный объект
    """

    objects = MovementEntryManager()

    movement_list = models.ForeignKey(
        MovementList,
        on_delete=models.CASCADE,
        verbose_name="Производственный объект"
    )
    employee = models.OneToOneField(
        Employee,
        on_delete=models.RESTRICT,
        null=True,
        verbose_name="Заезжающий/отъезжающий сотрудник"
    )
    creator = models.ForeignKey(
        get_user_model(),
        on_delete=models.SET_NULL,
        null=True,
        verbose_name="Кем создана"
    )
    creation_datetime = models.DateTimeField(
        "Время создания",
        auto_now_add=True
    )
    last_modified = models.DateTimeField(
        "Время последнего изменения",
        auto_now=True
    )
    is_deleted = models.BooleanField(
        "Удалён?",
        default=False
    )
    was_modified = models.BooleanField(
        "Был ли список изменен?",
        default=False
    )

    @property
    def was_changed(self):
        """
        Возвращает True, если запись была изменена, иначе False
        """
        return self.was_modified

    def get_url_kwargs(self):
        return {
            "facility_slug": self.movement_list.facility.slug,
            "list_id": self.movement_list.pk,
            "entry_id": self.pk,
        }

    def get_add_url(self):
        kwargs = self.get_url_kwargs()
        del kwargs["entry_id"]
        return reverse(
            "movement-list-entries-add",
            kwargs=kwargs,
        )

    def get_delete_url(self):
        kwargs = self.get_url_kwargs()
        return reverse(
            "movement-list-entry-delete",
            kwargs=kwargs,
        )

    def get_edit_url(self):
        kwargs = self.get_url_kwargs()
        return reverse(
            "movement-list-entry-edit",
            kwargs=kwargs,
        )

    def get_history_url(self):
        kwargs = self.get_url_kwargs()
        return reverse(
            "movement-list-entry-history",
            kwargs=kwargs,
        )

    def is_creator(self, user):
        return self.creator == user

    def has_change_perm(self, user):
        is_creator = self.is_creator(user)
        can_change_owned = user.has_perm("main.change_owned_movemententry")
        can_change = user.has_perm("main.change_movemententry")
        return is_creator and can_change_owned or can_change

    def has_delete_perm(self, user):
        can_delete_owned = user.has_perm("main.delete_owned_movemententry")
        is_creator = self.is_creator(user)
        can_delete = user.has_perm("main.delete_movemententry")
        return is_creator and can_delete_owned or can_delete

    def __str__(self):
        datetime = self.creation_datetime
        return "Время создания %s.%s.%s %s:%s" % (
            datetime.day,
            datetime.month,
            datetime.year,
            datetime.hour,
            datetime.minute,
        )

    class Meta:

        verbose_name = "Запись о заезде/выезде"
        verbose_name_plural = "Записи о заездах/выездах"

        permissions = [
            (
                "change_owned_movemententry",
                "Право изменения записи созданной пользователем"
            ),
            (
                "delete_owned_movemententry",
                "Право удаления записи созданной пользователем"
            ),
        ]


class MovementEntryHistory(HistoryMixin):
    """
    История изменений записи
    """

    modified_entry = models.ForeignKey(
        MovementEntry,
        on_delete=models.CASCADE
    )

    def get_change_states(self):
        prev_state = next(
            serializers.deserialize("json", self.serialized_prev_delta)
        ).object
        post_state = next(
            serializers.deserialize("json", self.serialized_post_delta)
        ).object
        states = {
            "prev_state": prev_state,
            "post_state": post_state,
        }
        return states

    class Meta:
        verbose_name = "Состояние записи"
        verbose_name_plural = "Состояния записей"

main/models/facility.py
from django.db import models
from django.urls import reverse


class FacilityObject(models.Model):

    name = models.CharField(
        "Название производственного объекта",
        max_length=100,
        unique=True
    )
    slug = models.SlugField(
        "Уникальная строка идентификатор (slug)",
        max_length=100,
        unique=True
    )

    def get_url_kwargs(self):
        kwargs = {
            "facility_slug": self.slug,
        }
        return kwargs

    def get_absolute_url(self):
        kwargs = self.get_url_kwargs()
        return reverse(
            "movement-lists",
            kwargs=kwargs
        )

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Производственный объект"
        verbose_name_plural = "Производственные объекты"

main/models/history.py
from django.db import models
from django.contrib.auth import get_user_model


class HistoryMixin(models.Model):

    modified_by = models.ForeignKey(
        get_user_model(),
        on_delete=models.SET_NULL,
        null=True
    )
    modified_datetime = models.DateTimeField("Время внесения изменений")
    serialized_prev_delta = models.TextField("Данные до изменения")
    serialized_post_delta = models.TextField("Данные после изменения")

    class Meta:
        abstract = True

main/forms.py
from django import forms
from django.utils import timezone
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit

from .models import MovementList, Employee, MovementEntry
from .widgets import ListTextWidget


class CustomUserCreationForm(UserCreationForm):

    class Meta:
        model = get_user_model()
        fields = UserCreationForm._meta.fields +\
            ("first_name", "last_name", "patronymic", "position")


class CustomUserChangeForm(UserChangeForm):
    pass


class CreateMovementListForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        _user_perms = kwargs.pop("perms", None)
        super(CreateMovementListForm, self).__init__(*args, **kwargs)
        if "main.set_watch_field" not in _user_perms:
            self.fields["watch"].widget = forms.HiddenInput()

    field_order = [
        "list_type",
        "move_date",
        "move_time",
        "place",
    ]

    move_date = forms.DateField(
        widget=forms.DateInput(
            attrs={
                "placeholder": "25.10.2020",
                "type": "date",
                "min": timezone.now().strftime("%Y-%m-%d")
            }
        ),
        label="Дата"
    )
    move_time = forms.TimeField(
        widget=forms.TimeInput(
            attrs={
                "placeholder": "14:30",
                "type": "time",
            }
        ),
        label="Время"
    )

    class Meta:
        model = MovementList
        fields = ["list_type", "place", "watch"]
        widgets = {
            "place": forms.TextInput(
                attrs={
                    "placeholder": "С какого места выезжает/заезжает сотрудник"
                },
            ),
        }


class EditMovementListForm(forms.Form):

    def __init__(self, *args, **kwargs):
        _user_perms = kwargs.pop("perms", None)
        super(EditMovementListForm, self).__init__(*args, **kwargs)
        if "main.set_watch_field" not in _user_perms:
            self.fields["watch"].widget = forms.HiddenInput()

    move_date = forms.DateField(
        widget=forms.DateInput(
            format=('%Y-%m-%d'),
            attrs={
                "type": "date",
                "min": timezone.now().strftime("%Y-%m-%d")
            }
        ),
        label="Дата"
    )
    move_time = forms.TimeField(
        widget=forms.TimeInput(
            attrs={
                "type": "time",
            }
        ),
        label="Время"
    )
    place = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "placeholder": "С какого места выезжает/заезжает сотрудник",
            },
        ),
        label="Место заезда/выезда",
        required=False
    )
    watch = forms.CharField(
        label="Вахта",
        required=False,
    )


class CreateMovementEntryForm(forms.Form):

    first_name = forms.CharField(
        min_length=2,
        max_length=40,
        label="Имя сотрудника",
    )
    last_name = forms.CharField(
        min_length=2,
        max_length=40,
        label="Фамилия сотрудника",
    )
    patronymic = forms.CharField(
        min_length=2,
        max_length=40,
        label="Отчество сотрудника",
        required=False,
    )
    position = forms.CharField(
        min_length=0,
        max_length=100,
        label="Должность",
        required=False,
    )

    is_senior = forms.BooleanField(
        label="Старший",
        required=False,
    )

    field_order = [
        "first_name",
        "last_name",
        "patronymic",
        "position",
    ]

    def __init__(self, *args, **kwargs):
        _suggestions = kwargs.pop("suggestions", None)
        _user_perms = kwargs.pop("perms", None)
        super(CreateMovementEntryForm, self).__init__(*args, **kwargs)

        self.fields["first_name"].widget = ListTextWidget(
            attrs={"placeholder": "Иван", "autocomplete": "off"},
            data_list=_suggestions.get("first_name", []),
            name="first_name_sug"
        )
        self.fields["last_name"].widget = ListTextWidget(
            attrs={"placeholder": "Иванов", "autocomplete": "off"},
            data_list=_suggestions.get("last_name", []),
            name="last_name_sug"
        )
        self.fields["patronymic"].widget = ListTextWidget(
            attrs={"placeholder": "Иванович", "autocomplete": "off"},
            data_list=_suggestions.get("patronymic", []),
            name="patronymic_sug"
        )
        self.fields["position"].widget = ListTextWidget(
            attrs={"placeholder": "Водитель", "autocomplete": "off"},
            data_list=_suggestions.get("position", []),
            name="position_sug",
        )

        if "main.can_set_is_senior" not in _user_perms:
            self.fields["is_senior"].widget = forms.HiddenInput()


class EditMovementEntryForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        _user_perms = kwargs.pop("perms", None)
        super(EditMovementEntryForm, self).__init__(*args, **kwargs)

        if "main.can_set_is_senior" not in _user_perms:
            self.fields["is_senior"].widget = forms.HiddenInput()

    class Meta:
        model = Employee
        fields = "__all__"


class SearchEntryForm(forms.Form):

    def __init__(self, action, *args, **kwargs):
        _suggestions = kwargs.pop("suggestions", None)
        super().__init__(*args, **kwargs)
        self.helper = FormHelper(self)
        self.helper.disable_csrf = True
        self.helper.form_method = "GET"
        self.helper.form_action = action
        self.helper.add_input(Submit("submit", "Найти"))
        self.fields["search_request"].widget = ListTextWidget(
            attrs={
                "placeholder": "Иван Иванов Иванович",
                "autocomplete": "off"
            },
            data_list=_suggestions,
            name="search_request"
        )

    PREDICATS = [
        ("EMPLOYEES", "ФИО сотрудника"),
        ("USERS", "ФИО ответственного"),
    ]

    search_request = forms.CharField(label="Запрос")
    predicat = forms.ChoiceField(
        label="Искать по",
        widget=forms.Select(),
        choices=PREDICATS,
    )


class SearchListForm(forms.Form):

    def __init__(self, action, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper(self)
        self.helper.disable_csrf = True
        self.helper.form_method = "GET"
        self.helper.form_action = action
        self.helper.add_input(Submit("submit", "Найти"))

    search_date = forms.DateField(
        widget=forms.DateInput(
            attrs={
                "type": "date",
                "min": timezone.now().strftime("%Y-%m-%d")
            }
        ),
        label="Дата"
    )

main/views/base.py
from django.views.generic.base import RedirectView


class DefaultRedirect(RedirectView):
    """
    Редирект на страницу производственного объекта по умолчанию
    """

    permanent = False
    pattern_name = "movement-lists"

main/views/mixins.py
from django.shortcuts import get_object_or_404, get_list_or_404

from ..models import FacilityObject, MovementList


class FacilityMixin:

    @property
    def related_facility(self):
        return get_object_or_404(
            FacilityObject, slug=self.kwargs["facility_slug"]
        )

    @property
    def all_facilities(self):
        return get_list_or_404(FacilityObject.objects.all())


class FacilityListMixin(FacilityMixin):

    @property
    def related_list(self):
        return get_object_or_404(
            MovementList, pk=self.kwargs["list_id"]
        )

main/templates/main/movement-list-entries/movement-list-entries-add.html
{% extends "../../base/base.html" %}

{% load breadcrumbs %}

{% block meta_title %}
Добавление записи
{% endblock meta_title %}

{% block main_content %}
<div class="container-lg">
  <div class="row">
    <div class="col-md">
      {% breadcrumbs links %}
      <ul class="nav nav-pills">
        <li class="nav-item">
          <a class="nav-link" href="{{ related_list.get_absolute_url }}">Записи</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" href="{% url 'movement-list-entries-add' facility_slug=related_facility.slug list_id=related_list.pk %}">
          Добавить запись
          <i class="fas fa-plus-circle"></i>
          </a>
        </li>
      </ul>
    </div>
  </div>

  <div class="row mt-2">
    <div class="col-md">
      <div class="card mt-4">
        {% url 'movement-list-entries-add' facility_slug=related_facility.slug list_id=related_list.pk as action %}
        {% with title="Добавление записи" action=action method="POST" form=form button_value="Создать" %}
        {% include "../../includes/crispy-form.html" %}
        {% endwith %}
      </div>
    </div>
  </div>
</div>
{% endblock main_content %}

main/templates/main/movement-list-entries/movement-list-entries-delete.html
{% extends "../../base/base.html" %}

{% load crispy_forms_tags %}

{% block meta_title %}
Подтверждение удаления
{% endblock meta_title %}

{% block main_content %}
<div class="container-lg">
  <div class="row justify-content-center">
    <div class="col-md-6 d-flex justify-content-center">
      <div class="card mt-4">
        <div class="card-body">
          <h2 class="card-title h5">Подтверждение удаления</h5>
          <p class="card-text">
          Вы уверены, что хотите удалить эту запись?<br>
          После этого действия с записью будут недоступны
          </p>
          <form action="{% url 'movement-list-entry-delete' facility_slug=related_facility.slug list_id=related_list.pk entry_id=entry_id %}" method="POST">
            {% csrf_token %}
            {{ form|crispy }}
            <div class="d-flex">
              {% include "../../includes/backbtn.html" %}
              <button type="submit" class="btn btn-danger ml-auto">Подтвердить</button>
            </div>
          </form>
        </div>  
      </div>
    </div>
  </div>
</div>
{% endblock main_content %}

main/templates/main/movement-list-entries/movement-list-entries-edit.html
{% extends "../../base/base.html" %}

{% load breadcrumbs %}

{% block meta_title %}
Редактирование записи
{% endblock meta_title %}

{% block main_content %}
<div class="container-lg">
  <div class="row">
    <div class="col-md">
      {% breadcrumbs links %}
      <div class="card mt-4">
        {% url 'movement-list-entry-edit' facility_slug=related_facility.slug list_id=related_list.pk entry_id=entry_id as action %}
        {% with title="Редактирование записи" action=action method="POST" form=form button_value="Подтвердить" %}
        {% include "../../includes/crispy-form.html" %}
        {% endwith %}
      </div>
    </div>
  </div>
</div>
{% endblock main_content %}

main/templates/main/movement-list-entries/movement-list-entries-print.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Список {{ related_list.list_type_humanize }}ов</title>
  <style>
  table {
    width: 100%;
  }

  th, td {
    padding: 0.4em 0.8em;
  }

  table, th, td {
    border: 1px solid black;
    border-collapse: collapse;
  }

  .senior-row {
    background-color: #ffeeba;
  }
  </style>
</head>
<body>
  <h1 style="font-size: 1.4rem; text-align: center;">
    {{ header }}, {{ related_list.list_type_humanize }} 
    на {{ related_list.scheduled_datetime|date:"d E Y H:i"}}
  </h1>
  <p style="font-size: 1.1rem;">
    Место {{ related_list.list_type_humanize }}а: {{ related_list.place }}
  </p>
  <table>
    <tr>
      <th style="width: 5%;">#</th>
      <th>ФИО</th>
      <th>Должность</th>
    </tr>
    {% for entry in entries %}
    {% if entry.employee.is_senior %}
    <tr class="senior-row">
    {% else %}
    <tr>
    {% endif %}
      <td style="text-align: center;">{{ forloop.counter }}</td>
      <td>{{ entry.employee.initials }}</td>
      <td>{{ entry.employee.position }}</td>
    </tr>
    {% endfor %}
  </table>
</body>
</html>

main/templates/main/movement-list-entries/movement-list-entries.html
{% extends "../../base/base.html" %}

{% load crispy_forms_tags %}
{% load breadcrumbs %}

{% comment %} 
Шаблон для отображения списка записей о заездах/выездах сотрудников
{% endcomment %}

{% block meta_title %}
{{ related_facility }} | Записи
{% endblock meta_title %}

{% block main_content %}
<div class="container-lg">
  <div class="row">
    <div class="col-md">
      {% if messages %}
      <ul class="list-unstyled">
        {% for message in messages %}
        <li class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
          {{ message }}
          <button type="button" class="close" data-dismiss="alert" aria-label="Закрыть">
            <span aria-hidden="true"><i class="fas fa-times"></i></span>
          </button>
        </li>
        {% endfor %}
      </ul>
      {% endif %}

      {% breadcrumbs links %}

      <ul class="nav nav-pills">
        {% if perms.main.add_movemententry and not related_list.is_deleted %}
        <li class="nav-item">
          <a class="nav-link active" href="{{ related_list.get_absolute_url }}">Записи</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'movement-list-entries-add' facility_slug=related_facility.slug list_id=related_list.pk %}">
          Добавить запись
          <i class="fas fa-plus-circle"></i>
          </a>
        </li>
        {% endif %}
        <li class="nav-item btn-group ml-auto" role="group">
          <a
          class="btn btn-outline-primary"
          href="{% url 'movement-list-entries-print' facility_slug=related_facility.slug list_id=related_list.pk %}"
          aria-label="Печать"
          >
            <i class="fas fa-print"></i>
          </a>
          <button
            type="button"
            class="btn btn-outline-primary"
            data-toggle="modal"
            data-target="#searchModal"
          >
            Поиск
          </button>
          {% if request.GET %}
          <a class="btn btn-outline-primary" href="{{ related_list.get_absolute_url }}">Сбросить фильтр</a>
          {% endif %}
        </li>
      </ul>
    </div>
  </div>

  <div class="row mt-2">
    <div class="col-md">
      <ul class="list-unstyled">
        <li>
          <p class="h5 mt-4">
            Дата и время {{ related_list.list_type_humanize }}а: 
            {{related_list.scheduled_datetime|date:"d E Y H:i"}}
          </p>
        </li>
        <li>
          <p class="h5">Место {{ related_list.list_type_humanize }}а: 
          {% if related_list.place %}
          {{ related_list.place }}
          {% else %}
          не указано
          {% endif %}
          </p>
        </li>
        <li>
          <p class="h5">Вахта: 
          {% if related_list.watch %}
          {{ related_list.watch }}
          {% else %}
          не указана
          {% endif %}
          </p>
        </li>
      </ul>
      {% if entries %}
        {% if user.is_authenticated %}
          {% include "../../includes/movement-list-entries-detailed.html" with entries=entries %}
        {% else %}
          <div class="mt-4">
          {% include "../../includes/movement-list-entries-table.html" with entries=entries %}
          </div>
        {% endif %}
      {% else %}
      <p class="h4 mt-4">Записи отсутствуют</p>
      {% endif %}
    </div>
  </div>

  {% comment %} Пагинация записей
  {% if paginator.num_pages and paginator.num_pages > 1 %}
  <footer class="row mt-4">
    <div class="col">
      {% if paginator.num_pages > 1 %}
      <footer class="row mt-4">
        <div class="col">
          {% include "../../includes/paginator.html" %}
        </div>
      </footer>
      {% endif %}
    </div>
  </footer>
  {% endif %}
</div> {% endcomment %}

<div class="modal fade" id="searchModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Поиск по записям</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true"><i class="fas fa-times"></i></span>
        </button>
      </div>
      <div class="modal-body">
        {% crispy search_form search_form.helper %}
      </div>
    </div>
  </div>
</div>

{% endblock main_content %}

main/templates/main/movement-list-entries/movement-list-entry-history.html
{% extends "../../base/base.html" %}

{% load breadcrumbs %}

{% block meta_title %}
История изменений
{% endblock meta_title %}

{% block main_content %}
<div class="container-lg">
  <div class="row">
    <div class="col-md">
        {% breadcrumbs links %}
      </ul>
    </div>
  </div>
  <div class="row">
    <div class="col-md">
      <div class="mt-4">
        {% if history_entries %}
        <ul class="list-unstyled">
          {% for entry in history_entries %}
          <li class="card shadow-sm mt-2">
            <div class="card-body">
              <h3 class="card-title h4">Изменения от {{ entry.meta.modified_datetime }}</h3>
              <p class="card-text">Внесены ответственным {{ entry.meta.modified_by.initials }}</p>
              <table class="table">
                <thead>
                  <tr>
                    <th scope="col">Поле</th>
                    <th scope="col">До изменений</th>
                    <th scope="col">После изменений</th>
                  </tr>
                </thead>
                <tbody>
                  <tr>
                    <th scope="row">Имя</th>
                    <td>{{ entry.prev_state.first_name }}</td>
                    <td>{{ entry.post_state.first_name }}</td>
                  </tr>
                  <tr>
                    <th scope="row">Фамилия</th>
                    <td>{{ entry.prev_state.last_name }}</td>
                    <td>{{ entry.post_state.last_name }}</td>
                  </tr>
                  <tr>
                    <th scope="row">Отчество</th>
                    <td>{{ entry.prev_state.patronymic }}</td>
                    <td>{{ entry.post_state.patronymic }}</td>
                  </tr>
                  <tr>
                    <th scope="row">Позиция</th>
                    <td>{{ entry.prev_state.position }}</td>
                    <td>{{ entry.post_state.position }}</td>
                  </tr>
                </tbody>
              </table>
            </div>
          </li>
          {% endfor %}
        </ul>
        {% else %}
        <h3 class="h5 card-title">Нет изменений</h2>
        {% endif %}
      </div>
    </div>
  </div>
</div>
{% endblock main_content %}